import { mkdirSync, existsSync, writeFileSync, readFileSync, copyFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import {
  COG_DIR, COG_MEMORY_DIR, COG_META_DIR, COG_GLACIER_DIR, COG_SOURCES_DIR,
  COG_DOMAINS_PATH, COG_SYSTEM_PATH,
} from "../paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BUNDLED_SYSTEM_MD = join(__dirname, "default-system.md");

const HOT_MEMORY_SEED = `<!-- L0: Cross-domain priorities and identity — <50 lines -->
# Hot Memory

## Identity

(Write a short identity/context line here — who the user is, what they care about.)

## Active Priorities

(Top 3-5 things the user is actively working on or watching.)

## Strategic Context

(Phase-of-life notes, recent pivots, current season.)
`;

const PATTERNS_SEED = `<!-- L0: Universal interaction patterns distilled from self-observations — ≤70 lines / 5.5 KB -->
# Patterns

_Distilled rules that apply across all domains. Loaded into every session. Kept lean — domain-specific patterns belong in satellite files._
`;

const SELF_OBS_SEED = `<!-- L0: Append-only log of notable interactions — distilled into patterns.md -->
# Self-Observations

_Append-only. Each entry: \`- YYYY-MM-DD [tags]: <observation>\`. Periodically distilled into \`patterns.md\` by cog-reflect._
`;

const IMPROVEMENTS_SEED = `<!-- L0: Wishlist, repair notes, rule-drift issues for the memory system itself -->
# Improvements

## Ideas

## Repairs

## Rule Drift
`;

const SCENARIO_CAL_SEED = `<!-- L0: Tracks prediction accuracy of past scenarios — updated by cog-reflect -->
# Scenario Calibration

_When a scenario's outcome is known, log the delta here so future scenarios calibrate confidence._
`;

const REFLECT_CURSOR_SEED = `<!-- L0: Ingestion cursor for cog-reflect — last conversation_log id consumed -->
# Reflect Cursor

last_conversation_id: 0
last_run: never
source: ~/.max/cog/memory/cog-meta/recent-conversations.md
`;

const BRIEFING_BRIDGE_SEED = `<!-- L0: Auto-generated stale-item digest — consumed by cog-foresight -->
# Briefing Bridge

_Auto-generated by cog-housekeeping. Do not edit manually._
`;

const FORESIGHT_NUDGE_SEED = `<!-- L0: Latest strategic nudge — one per foresight run, overwrites previous -->
# Foresight Nudge

_Overwritten each run of cog-foresight._
`;

const RECENT_CONVO_SEED = `<!-- L0: Latest conversation dump from cog-scheduler — input to cog-reflect -->
# Recent Conversations

_Overwritten by cog-scheduler before each cog-reflect run. Do not edit manually._
`;

const GLACIER_INDEX_SEED = `<!-- L0: Catalog of archived memory files — auto-generated by cog-housekeeping -->
# Glacier Index

_Auto-generated. Each entry lists a glacier file with its type, domain, tags, date range, entry count, and summary._
`;

const LINK_INDEX_SEED = `<!-- L0: Backlink index — auto-generated by cog-housekeeping -->
# Link Index

_Auto-generated. For each memory file, lists the other files that link to it._

| Target | Linked from |
|--------|-------------|
`;

const DOMAINS_SEED = `# COG Domains Manifest
# Single source of truth for all registered domains. Managed by cog-setup.

domains:
  - id: personal
    path: memory/personal
    type: life
    triggers: [personal, family, health, calendar, home, habits, philosophy]
    description: Day-to-day personal life — family, health, calendar, habits.
    files:
      - hot-memory.md
      - observations.md
      - action-items.md
      - entities.md
      - calendar.md
`;

// Seed files for the default "personal" domain
const PERSONAL_SEEDS: Record<string, string> = {
  "hot-memory.md": `<!-- L0: Personal domain current-state summary — <50 lines -->
# Personal — Hot Memory

## Current Focus

## Active Tasks

## Watch List
`,
  "observations.md": `<!-- L0: Timestamped personal observations — append-only -->
# Personal Observations

_Append-only. Format: \`- YYYY-MM-DD [tags]: <observation>\`._
`,
  "action-items.md": `<!-- L0: Personal task list — checkboxes, optional due/pri/domain metadata -->
# Personal Action Items

_Format: \`- [ ] task | due:YYYY-MM-DD | pri:critical/high/med/low | added:YYYY-MM-DD\`. Mark done with \`- [x] task (done YYYY-MM-DD)\`._
`,
  "entities.md": `<!-- L0: Personal entities registry — people, places, named things (3-line compact) -->
# Personal Entities

_3-line registry: \`### Name (relationship)\` / key facts / \`status | last | → [[link]]\`._
`,
  "calendar.md": `<!-- L0: Scheduled personal events — edit in place -->
# Personal Calendar

## Upcoming

## Recurring
`,
  "patterns.md": `<!-- L0: Personal-domain patterns — satellite file, soft cap 30 lines -->
# Personal Patterns

_Domain-specific rules. Loaded only when cog-personal is active._
`,
};

function writeIfMissing(path: string, content: string): void {
  if (!existsSync(path)) {
    writeFileSync(path, content);
  }
}

function installSystemMd(): void {
  if (existsSync(COG_SYSTEM_PATH)) return;
  try {
    copyFileSync(BUNDLED_SYSTEM_MD, COG_SYSTEM_PATH);
  } catch (err) {
    // Bundled file missing in unexpected build layout — write a minimal stub so
    // the daemon still boots; the user can replace it later.
    const fallback = `# Max + COG\n\n(Bundled SYSTEM.md was not found at ${BUNDLED_SYSTEM_MD}. Check your install.)\n\nError: ${err instanceof Error ? err.message : err}\n`;
    writeFileSync(COG_SYSTEM_PATH, fallback);
  }
}

/**
 * Create the full ~/.max/cog/ tree on first run. Returns true when it had to
 * create the root COG_DIR itself (i.e. first-time install); returns false if
 * the tree already existed.
 */
export function ensureCogStructure(): boolean {
  const firstTime = !existsSync(COG_DIR);

  mkdirSync(COG_MEMORY_DIR, { recursive: true });
  mkdirSync(COG_META_DIR, { recursive: true });
  mkdirSync(join(COG_META_DIR, "scenarios"), { recursive: true });
  mkdirSync(COG_GLACIER_DIR, { recursive: true });
  mkdirSync(COG_SOURCES_DIR, { recursive: true });
  mkdirSync(join(COG_MEMORY_DIR, "personal"), { recursive: true });

  installSystemMd();

  writeIfMissing(COG_DOMAINS_PATH, DOMAINS_SEED);
  writeIfMissing(join(COG_MEMORY_DIR, "hot-memory.md"), HOT_MEMORY_SEED);
  writeIfMissing(join(COG_MEMORY_DIR, "link-index.md"), LINK_INDEX_SEED);

  writeIfMissing(join(COG_META_DIR, "patterns.md"), PATTERNS_SEED);
  writeIfMissing(join(COG_META_DIR, "self-observations.md"), SELF_OBS_SEED);
  writeIfMissing(join(COG_META_DIR, "improvements.md"), IMPROVEMENTS_SEED);
  writeIfMissing(join(COG_META_DIR, "scenario-calibration.md"), SCENARIO_CAL_SEED);
  writeIfMissing(join(COG_META_DIR, "reflect-cursor.md"), REFLECT_CURSOR_SEED);
  writeIfMissing(join(COG_META_DIR, "briefing-bridge.md"), BRIEFING_BRIDGE_SEED);
  writeIfMissing(join(COG_META_DIR, "foresight-nudge.md"), FORESIGHT_NUDGE_SEED);
  writeIfMissing(join(COG_META_DIR, "recent-conversations.md"), RECENT_CONVO_SEED);

  writeIfMissing(join(COG_GLACIER_DIR, "index.md"), GLACIER_INDEX_SEED);

  for (const [name, content] of Object.entries(PERSONAL_SEEDS)) {
    writeIfMissing(join(COG_MEMORY_DIR, "personal", name), content);
  }

  return firstTime;
}

/** Read a memory file relative to ~/.max/cog/memory/. Returns empty string if missing. */
export function readMemoryFile(relPath: string): string {
  const full = join(COG_MEMORY_DIR, relPath);
  if (!existsSync(full)) return "";
  try {
    return readFileSync(full, "utf-8");
  } catch {
    return "";
  }
}

/** Read a file under ~/.max/cog/. Returns empty string if missing. */
export function readCogFile(relPath: string): string {
  const full = join(COG_DIR, relPath);
  if (!existsSync(full)) return "";
  try {
    return readFileSync(full, "utf-8");
  } catch {
    return "";
  }
}
